const cfg=window.OBRA_SUPABASE,body=document.querySelector('#schedule-body'),toast=document.querySelector('#toast');
let db=null,user=null,profile=null,projects=[],tasks=[],activeFilter='all',selectedProject=null,originalWorkbook=null,originalFileName='',passwordRecoveryMode=location.hash.includes('type=recovery')||location.hash.includes('type=invite');
const $=selector=>document.querySelector(selector),changed=t=>!t.summary&&t.actual!==t.originalActual;
const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4000)}
function key(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9%]/g,'')}
function find(headers,names){return headers.findIndex(h=>names.some(n=>h===n||h.includes(n)))}
function percent(value){if(value===undefined||value===null||value==='')return 0;const raw=String(value).trim(),hasPercent=raw.includes('%'),source=raw.replace('%',''),normalized=source.includes(',')?source.replace(/\./g,'').replace(',','.'):source,n=Number(normalized);if(!Number.isFinite(n))return 0;return Math.round(Math.max(0,Math.min(100,!hasPercent&&n>=0&&n<=1?n*100:n)))}
function headerRow(rows){let best={index:-1,score:0};rows.slice(0,30).forEach((row,index)=>{const h=row.map(key),score=['atividade','tarefa','task','nome','eap','wbs','id','resumo','planejado','previsto','concluido','realizado','avanco'].filter(word=>h.some(x=>x.includes(word))).length;if(score>best.score)best={index,score}});return best.score?best.index:-1}
function setLoginMessage(text,isError=true){$('#login-message').textContent=text;$('#login-message').style.color=isError?'var(--red)':'var(--teal)'}
function setRecoveryMessage(text,isError=true){const target=passwordRecoveryMode?'#password-message':'#forgot-message';$(target).textContent=text;$(target).style.color=isError?'var(--red)':'var(--teal)'}
function setLoginView(view){
  $('#login-form').hidden=view!=='login';
  $('#forgot-password-form').hidden=view!=='forgot';
  $('#password-recovery-form').hidden=view!=='recovery';
  if(view==='forgot'){$('#forgot-email').value=$('#login-email').value;setRecoveryMessage('')}
  if(view==='recovery')setRecoveryMessage('');
}
async function start(){
  if(!window.supabase||!cfg?.url||!cfg?.publishableKey){setLoginMessage('Não consegui carregar a conexão do Supabase. Atualize a página ou confira a configuração.');return}
  db=window.supabase.createClient(cfg.url,cfg.publishableKey);
  if(passwordRecoveryMode)setLoginView('recovery');
  db.auth.onAuthStateChange((event,session)=>{
    if(event==='PASSWORD_RECOVERY'){passwordRecoveryMode=true;setLoginView('recovery');return}
    if(passwordRecoveryMode)return;
    if(event==='SIGNED_IN'&&session?.user)void enterApp(session.user);
    else if(event==='SIGNED_OUT')leaveApp();
  });
  const {data:{session}}=await db.auth.getSession();
  if(session&&!passwordRecoveryMode)await enterApp(session.user);
}
async function enterApp(authUser){user=authUser;const {data:p,error}=await db.from('profiles').select('id,email,display_name,role').eq('id',user.id).maybeSingle();if(error||!p){leaveApp();setLoginMessage('Perfil não encontrado. Execute schema.sql e confirme seu perfil no Supabase.');return}profile=p;$('#login-screen').hidden=true;$('#app-main').hidden=false;$('#logout-button').hidden=false;$('#avatar').textContent=(p.display_name||p.email||'?').slice(0,2).toUpperCase();$('#user-label').textContent=p.display_name||p.email;$('#role-label').textContent=p.role==='admin'?'Planejamento':'Engenheiro';$('#admin-tools').hidden=p.role!=='admin';$('#admin-submissions').hidden=p.role!=='admin';$('#engineer-panel').hidden=p.role==='admin';$('#export-button').hidden=p.role!=='admin';await loadProjects();if(p.role==='admin'){await loadEngineers();await loadSubmissions()} }
function leaveApp(){user=null;profile=null;projects=[];tasks=[];selectedProject=null;$('#app-main').hidden=true;$('#login-screen').hidden=false;$('#logout-button').hidden=true;$('#project-select').innerHTML='<option value="">Selecione uma obra</option>';if(!passwordRecoveryMode)setLoginView('login');render()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();setLoginMessage('Entrando…',false);const {error}=await db.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)setLoginMessage('Não foi possível entrar. Confira o e-mail e a senha.');});
$('#show-forgot-password').onclick=()=>setLoginView('forgot');
$('#back-to-login').onclick=()=>setLoginView('login');
$('#forgot-password-form').addEventListener('submit',async e=>{
  e.preventDefault();const button=$('#send-reset-link');button.disabled=true;setRecoveryMessage('Enviando instruções…',false);
  const {error}=await db.auth.resetPasswordForEmail($('#forgot-email').value.trim(),{redirectTo:window.location.origin+window.location.pathname});
  button.disabled=false;
  if(error){setRecoveryMessage('Não foi possível enviar o e-mail agora. Tente novamente em alguns minutos.');return}
  setRecoveryMessage('Se esse e-mail estiver cadastrado, você receberá um link para redefinir a senha. Verifique também a caixa de spam.',false);
});
$('#password-recovery-form').addEventListener('submit',async e=>{
  e.preventDefault();const password=$('#new-password').value,confirmation=$('#confirm-password').value;
  if(password!==confirmation){setRecoveryMessage('As senhas não coincidem.');return}
  if(password.length<6){setRecoveryMessage('Use uma senha com pelo menos 6 caracteres.');return}
  const button=$('#save-new-password');button.disabled=true;setRecoveryMessage('Salvando nova senha…',false);
  const {error}=await db.auth.updateUser({password});
  button.disabled=false;
  if(error){setRecoveryMessage('Não foi possível atualizar a senha. Solicite um novo link e tente novamente.');return}
  passwordRecoveryMode=false;await db.auth.signOut();$('#new-password').value='';$('#confirm-password').value='';
  setLoginView('login');setLoginMessage('Senha definida com sucesso. Entre com sua nova senha.',false);
});
$('#logout-button').onclick=async()=>{await db.auth.signOut();notify('Você saiu do app.')};
async function loadProjects(preferredId){const {data,error}=await db.from('projects').select('id,name,source_file,created_at').order('name');if(error){notify('Não consegui carregar as obras. '+error.message);return}projects=data||[];const select=$('#project-select');select.innerHTML='<option value="">Selecione uma obra</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');const wanted=preferredId||selectedProject||projects[0]?.id||'';if(wanted&&projects.some(p=>p.id===wanted)){select.value=wanted;await loadProject(wanted)}else{selectedProject=null;tasks=[];render()}if(profile?.role==='admin')await loadAssignments()}
$('#project-select').onchange=()=>loadProject($('#project-select').value);
async function loadProject(projectId){selectedProject=projectId;const project=projects.find(p=>p.id===projectId);if(!project){tasks=[];render();return}$('#project-name').innerHTML=`<span class="dot"></span> ${esc(project.name)} <small>• ${project.source_file?'cronograma carregado':'obra'}</small>`;const {data:activities,error}=await db.from('activities').select('*').eq('project_id',projectId).order('sort_order');if(error){notify('Falha ao carregar atividades: '+error.message);return}const {data:latest,error:latestError}=await db.from('submissions').select('id,submitted_at,submitted_by').eq('project_id',projectId).order('submitted_at',{ascending:false}).limit(1).maybeSingle();if(latestError){notify('Falha ao carregar atualizações: '+latestError.message);return}let values=new Map();if(latest){const {data:items,error:itemError}=await db.from('submission_items').select('activity_id,actual_pct').eq('submission_id',latest.id);if(itemError){notify('Falha ao carregar percentuais: '+itemError.message);return}values=new Map((items||[]).map(x=>[x.activity_id,Number(x.actual_pct)]))}tasks=(activities||[]).map((a,index)=>({id:a.id,sortOrder:a.sort_order,activityId:a.activity_id,wbs:a.wbs||'',name:a.name,summary:a.is_summary,plan:Number(a.planned_pct),actual:values.has(a.id)?values.get(a.id):Number(a.initial_actual_pct),originalActual:values.has(a.id)?values.get(a.id):Number(a.initial_actual_pct),sourceSheet:a.source_sheet,sourceRow:a.source_row,sourceActualColumn:a.source_actual_column}));$('#last-update').textContent=latest?new Date(latest.submitted_at).toLocaleString('pt-BR'):'Nenhum envio ainda';$('#table-help').textContent=latest?'Percentuais do envio mais recente.':'Cronograma original; aguardando a primeira atualização.';render();if(profile?.role==='admin')await loadAssignments()}
function render(){const q=($('#search')?.value||'').toLowerCase();if(!tasks.length){body.innerHTML='<tr><td colspan="5" class="empty-state">Selecione uma obra para ver as atividades.</td></tr>';['attention-count','late-count','changed-count','all-count'].forEach(id=>$('#'+id).textContent='0');$('#planned-total').textContent='—';$('#actual-total').textContent='—';$('#actual-detail').textContent='aguardando cronograma';$('#actual-bar').style.width='0%';return}const visible=tasks.filter(t=>t.name.toLowerCase().includes(q)&&(activeFilter==='all'||activeFilter==='changed'&&changed(t)||activeFilter==='late'&&!t.summary&&t.actual<t.plan));body.innerHTML=visible.map(t=>{const variation=t.actual-t.plan,late=!t.summary&&variation<0;return `<tr class="${t.summary?'summary-row':''} ${changed(t)?'changed':''}"><td class="task-id" data-label="ID">${esc(t.activityId)}</td><td class="task-cell" data-label="Atividade"><span class="wbs">${esc(t.wbs)}</span>${esc(t.name)}${t.summary?' <span class="summary-label">RESUMO</span>':''}</td><td class="percent" data-label="Planejado">${t.plan}%</td><td data-label="Avanço informado">${t.summary?'<span class="not-editable">Não editável</span>':`<input class="actual-input" aria-label="Avanço de ${esc(t.name)}" type="number" inputmode="decimal" min="0" max="100" step="1" value="${t.actual}" data-id="${esc(t.id)}"/> %`}</td><td class="delta ${late?'negative':variation>0?'positive':''}" data-label="Variação">${variation>0?'+':''}${variation} p.p.</td></tr>`}).join('')||'<tr><td colspan="5" class="empty-state">Nenhuma atividade corresponde ao filtro selecionado.</td></tr>';const leaves=tasks.filter(t=>!t.summary),late=leaves.filter(t=>t.actual<t.plan).length,changes=leaves.filter(changed).length,actual=Math.round(leaves.reduce((s,t)=>s+t.actual,0)/(leaves.length||1)),plan=Math.round(leaves.reduce((s,t)=>s+t.plan,0)/(leaves.length||1));$('#attention-count').textContent=late;$('#late-count').textContent=late;$('#changed-count').textContent=changes;$('#all-count').textContent=tasks.length;$('#actual-total').textContent=actual+'%';$('#planned-total').textContent=plan+'%';$('#actual-bar').style.width=actual+'%';$('#actual-detail').textContent=actual===plan?'em linha com o planejado':`${Math.abs(plan-actual)} pontos ${actual<plan?'abaixo':'acima'} do planejado`}
body.addEventListener('change',e=>{if(!e.target.matches('.actual-input'))return;const t=tasks.find(x=>x.id===e.target.dataset.id);if(!t)return;t.actual=Math.max(0,Math.min(100,Number(e.target.value)||0));render()});
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{activeFilter=button.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===button));render()});$('#search').oninput=render;
$('#send-update').onclick=async()=>{if(!selectedProject)return notify('Selecione uma obra antes de enviar.');const items=tasks.filter(t=>!t.summary).map(t=>({activity_id:t.id,actual_pct:t.actual}));const {data,error}=await db.rpc('submit_progress',{target_project:selectedProject,items});if(error)return notify('Não foi possível enviar. '+error.message);tasks.forEach(t=>t.originalActual=t.actual);$('#last-update').textContent=new Date().toLocaleString('pt-BR');$('#table-help').textContent='Atualização enviada e registrada no histórico.';render();notify('Atualização enviada ao planejamento.');};
$('#import-button').onclick=async()=>{
  const button=$('#import-button'),file=$('#schedule-file').files[0],name=$('#new-project-name').value.trim()||file?.name.replace(/\.[^.]+$/,'');
  const emails=[...new Set($('#engineer-emails').value.split(/[,;\n]+/).map(x=>x.trim().toLowerCase()).filter(Boolean))];
  if(!file)return notify('Selecione um arquivo Excel ou CSV.');
  if(!name)return notify('Informe o nome da obra.');
  if(emails.some(email=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)))return notify('Confira os e-mails informados. Separe vários com vírgula ou linha.');
  let phase='Lendo o arquivo';
  button.disabled=true;button.textContent='Importando…';
  try{
    const buffer=await file.arrayBuffer(),wb=XLSX.read(buffer,{type:'array',raw:false,cellDates:true});let parsed=null;
    for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:'',raw:false});const hi=headerRow(rows);if(hi>=0){parsed={sheetName,rows,headerIndex:hi};break}}
    if(!parsed)throw Error('Não encontrei uma aba com atividades.');
    const headers=parsed.rows[parsed.headerIndex].map(key),cols={id:find(headers,['uniqueid','activityid','taskid','uid','id']),name:find(headers,['nomedetarefa','atividade','taskname','tarefa','task','nome']),wbs:find(headers,['eap','wbs','outline']),summary:find(headers,['resumo','summary']),plan:find(headers,['percentualplanejado','planejado','percentualanterior','anterior','previsto','baseline']),actual:find(headers,['percentualconcluido','percentcomplete','percentualexecutado','executado','realizado','avanco','concluido'])};
    if(cols.name<0)throw Error('Não encontrei a coluna Atividade/Nome da tarefa.');
    if(cols.actual<0)throw Error('Não encontrei a coluna de percentual executado/realizado.');
    const parsedActivities=[];
    parsed.rows.slice(parsed.headerIndex+1).forEach((row,i)=>{const activityName=String(row[cols.name]||'').trim();if(!activityName)return;const actual=percent(row[cols.actual]),plan=cols.plan<0?actual:percent(row[cols.plan]);parsedActivities.push({sort_order:parsedActivities.length,activity_id:String(cols.id<0?parsedActivities.length+1:row[cols.id]||parsedActivities.length+1),wbs:cols.wbs<0?'':String(row[cols.wbs]||''),name:activityName,is_summary:cols.summary>=0&&['sim','s','yes','true','1'].includes(key(row[cols.summary])),planned_pct:plan,initial_actual_pct:actual,source_sheet:parsed.sheetName,source_row:parsed.headerIndex+1+i,source_actual_column:cols.actual})});
    if(!parsedActivities.length)throw Error('Não encontrei atividades abaixo do cabeçalho.');
    phase='Criando o cadastro da obra';const {data:project,error:projectError}=await db.from('projects').insert({name,source_file:file.name,created_by:user.id}).select('id').single();if(projectError)throw projectError;
    phase='Enviando o arquivo original ao armazenamento';const path=`${project.id}/${file.name}`;const {error:uploadError}=await db.storage.from('schedule-files').upload(path,file,{contentType:file.type||'application/octet-stream'});if(uploadError)throw uploadError;
    phase='Salvando atividades do cronograma';for(let i=0;i<parsedActivities.length;i+=250){const batch=parsedActivities.slice(i,i+250).map(a=>({...a,project_id:project.id}));const {error}=await db.from('activities').insert(batch);if(error)throw error}
    let invited=0,associated=0,failed=[];
    for(const email of emails){const {data,error}=await db.functions.invoke('invite-engineer',{body:{email,projectId:project.id}});if(error||data?.error)failed.push(email+': '+(data?.error||error.message));else if(data.invited)invited++;else associated++}
    $('#new-project-name').value='';$('#schedule-file').value='';$('#engineer-emails').value='';await loadProjects(project.id);
    const result=`${parsedActivities.length} atividades importadas para ${name}.${emails.length? ` ${invited} convite(s) enviado(s), ${associated} engenheiro(s) já cadastrado(s).`:''}`;
    notify(failed.length?`${result} Convites pendentes: ${failed.join(' | ')}`:result);
  }catch(error){console.error(error);notify(`${phase}: ${error.message||'falha inesperada.'}`)}
  finally{button.disabled=false;button.textContent='Importar obra e convidar'}
};
async function loadEngineers(){const {data,error}=await db.from('profiles').select('id,email,display_name').eq('role','engineer').order('email');if(error){$('#engineer-select').innerHTML='<option value="">Erro ao carregar usuários</option>';notify(error.message);return}$('#engineer-select').innerHTML='<option value="">Selecione</option>'+(data||[]).map(p=>`<option value="${p.id}">${esc(p.display_name||p.email)} (${esc(p.email)})</option>`).join('')}
$('#assign-button').onclick=async()=>{const engineerId=$('#engineer-select').value;if(!selectedProject||!engineerId)return notify('Selecione uma obra e um engenheiro.');const {error}=await db.from('project_members').insert({project_id:selectedProject,user_id:engineerId,assigned_by:user.id});if(error)return notify(error.code==='23505'?'Este engenheiro já está atribuído a esta obra.':error.message);await loadAssignments();notify('Engenheiro atribuído à obra.')};
async function loadAssignments(){if(!selectedProject||profile?.role!=='admin')return;const {data,error}=await db.from('project_members').select('user_id').eq('project_id',selectedProject);if(error)return;const ids=(data||[]).map(x=>x.user_id);if(!ids.length){$('#assignment-status').textContent='Nenhum engenheiro atribuído a esta obra.';return}const {data:people}=await db.from('profiles').select('id,email,display_name').in('id',ids);$('#assignment-status').textContent='Acesso: '+(people||[]).map(x=>x.display_name||x.email).join(', ')}
async function loadSubmissions(){const {data:s,error}=await db.from('submissions').select('id,project_id,submitted_by,submitted_at').order('submitted_at',{ascending:false}).limit(20);if(error){$('#submission-list').textContent=error.message;return}if(!s?.length){$('#submission-list').textContent='Nenhuma atualização recebida ainda.';return}const projectIds=[...new Set(s.map(x=>x.project_id))],userIds=[...new Set(s.map(x=>x.submitted_by))];const [{data:p},{data:u}]=await Promise.all([db.from('projects').select('id,name').in('id',projectIds),db.from('profiles').select('id,email,display_name').in('id',userIds)]);const pm=new Map((p||[]).map(x=>[x.id,x.name])),um=new Map((u||[]).map(x=>[x.id,x.display_name||x.email]));$('#submission-list').innerHTML=s.map(x=>`<div class="submission-row"><span><b>${esc(pm.get(x.project_id)||'Obra')}</b><br><small>${esc(um.get(x.submitted_by)||'Engenheiro')}</small></span><small>${new Date(x.submitted_at).toLocaleString('pt-BR')}</small></div>`).join('')}
$('#export-button').onclick=async()=>{if(!selectedProject)return notify('Selecione uma obra para exportar.');const project=projects.find(p=>p.id===selectedProject);if(!project)return;const path=`${project.id}/${project.source_file}`;const {data:file,error}=await db.storage.from('schedule-files').download(path);if(error)return notify('Falha ao baixar o original. '+error.message);try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:false,cellDates:true});for(const t of tasks){if(t.summary||t.sourceActualColumn===null||t.sourceActualColumn===undefined)continue;const ws=wb.Sheets[t.sourceSheet];if(!ws)continue;const addr=XLSX.utils.encode_cell({r:t.sourceRow,c:t.sourceActualColumn});const cell=ws[addr]||{};const fraction=(String(cell.z||'').includes('%')||(typeof cell.v==='number'&&cell.v>=0&&cell.v<=1));ws[addr]={...cell,t:'n',v:fraction?t.actual/100:t.actual}}XLSX.writeFile(wb,`${project.name.replace(/[\\/:*?"<>|]/g,'_')}_atualizado.xlsx`);notify('Excel atualizado baixado.')}catch(e){notify('Falha ao gerar o Excel. '+e.message)}};
window.addEventListener('focus',()=>{if(profile?.role==='admin')loadSubmissions()});setInterval(()=>{if(profile?.role==='admin')loadSubmissions()},60000);
render();start();